sylius_grid:
    grids:
        jarekmajcher_sylius_gift_wrapper_plugin_admin_gift_wrap_method:
            driver:
                name: doctrine/orm
                options:
                    class: "%jarekmajcher_sylius_gift_wrapper_plugin.model.gift_wrap_method.class%"
            sorting:
                id: desc
            limits: [100, 200, 500]
            fields:
                id:
                    type: string
                    label: sylius.ui.id
                    sortable: ~
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
                position:
                    type: string
                    label: sylius.ui.position
                    sortable: ~
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
            filters: ~
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete